export const p101ExpectedViolations = [
  'modules/auth/api/alias-entry.ts controller may not consume Resend symbol Resend',
  'modules/auth/api/alias-entry.ts controller may not import provider SDK resend',
  'modules/auth/api/alias-entry.ts may not consume Resend symbol Resend outside modules/notifications/infrastructure',
  'modules/auth/api/alias-entry.ts may not import resend; Resend belongs in modules/notifications/infrastructure',
  'modules/auth/api/function-wrapper-entry.ts controller may not consume AWS SDK symbol StorageConditional',
  'modules/auth/api/function-wrapper-entry.ts may not consume AWS SDK symbol StorageConditional outside modules/media/infrastructure',
  'modules/auth/api/initializer-wrapper-entry.ts controller may not consume Prisma-origin symbol DataReference',
  'modules/auth/api/initializer-wrapper-entry.ts may not consume Prisma-origin symbol DataReference outside approved infrastructure adapters',
  'modules/auth/api/namespace-entry.ts controller may not consume AWS SDK symbol S3Client',
  'modules/auth/api/namespace-entry.ts controller may not import provider SDK @aws-sdk/client-s3',
  'modules/auth/api/namespace-entry.ts may not consume AWS SDK symbol S3Client outside modules/media/infrastructure',
  'modules/auth/api/namespace-entry.ts may not import @aws-sdk/client-s3; AWS SDK belongs in modules/media/infrastructure',
  'modules/auth/api/safe-decorator-entry.ts may not consume Prisma-origin symbol DataReference outside approved infrastructure adapters',
  'modules/auth/application/derived-consumer.ts may not consume AWS SDK symbol StorageConditional outside modules/media/infrastructure',
  'modules/auth/application/derived-consumer.ts may not consume Prisma-origin symbol DataClass outside approved infrastructure adapters',
  'modules/auth/application/derived-consumer.ts may not consume Prisma-origin symbol DataReference outside approved infrastructure adapters',
  'modules/auth/application/derived-consumer.ts may not consume Resend symbol MailAlias outside modules/notifications/infrastructure',
  'modules/auth/application/import-types.ts may not consume AWS SDK symbol import("../../../shared/restricted.barrel").ProviderTypes.StoragePort outside modules/media/infrastructure',
  'modules/auth/application/import-types.ts may not consume AWS SDK symbol import("../../../shared/restricted.barrel").StorageConditional outside modules/media/infrastructure',
  'modules/auth/application/import-types.ts may not consume Prisma-origin symbol import("../../../shared/restricted.barrel").DataReference outside approved infrastructure adapters',
  'modules/auth/application/import-types.ts may not consume Prisma-origin symbol import("@prisma/adapter-pg").PrismaPg outside approved infrastructure adapters',
  'modules/auth/application/import-types.ts may not consume Resend symbol import("../../../shared/restricted.barrel").MailAlias outside modules/notifications/infrastructure',
  'modules/auth/application/import-types.ts may not import @prisma/adapter-pg; Prisma access belongs in approved infrastructure adapters',
  'modules/auth/application/local-generated-client.ts may not consume Prisma-origin symbol PrismaClient outside approved infrastructure adapters',
  'modules/auth/application/local-generated-client.ts may not import ../../../generated/prisma; Prisma access belongs in approved infrastructure adapters',
  'modules/auth/application/public.ts application/public.ts may not export ApiContract; only same-module application type/interface contracts and Symbol DI tokens are public',
  'modules/auth/application/public.ts application/public.ts may not export ConcreteApplicationService; only same-module application type/interface contracts and Symbol DI tokens are public',
  'modules/auth/application/public.ts application/public.ts may not export DomainContract; only same-module application type/interface contracts and Symbol DI tokens are public',
  'modules/auth/application/public.ts application/public.ts may not export InfrastructureContract; only same-module application type/interface contracts and Symbol DI tokens are public',
  'modules/auth/application/public.ts application/public.ts may not export LocalConcreteService; only same-module application type/interface contracts and Symbol DI tokens are public',
  'modules/auth/application/public.ts application/public.ts may not export PLAIN_VALUE; only same-module application type/interface contracts and Symbol DI tokens are public',
  'modules/auth/application/public.ts application/public.ts may not export SharedContract; only same-module application type/interface contracts and Symbol DI tokens are public',
  'modules/auth/application/public.ts application/public.ts may not export concreteFactory; only same-module application type/interface contracts and Symbol DI tokens are public',
  'modules/auth/application/public.ts application/public.ts may not export localFactory; only same-module application type/interface contracts and Symbol DI tokens are public',
  'modules/auth/application/public.ts may not depend on modules/auth/api/public-source.ts',
  'modules/auth/application/public.ts may not depend on modules/auth/infrastructure/public-source.ts',
  'modules/auth/domain/import-types.ts crosses into modules/sites/domain/private.ts; cross-module imports must target application/public.ts',
  'modules/auth/domain/import-types.ts may not depend on modules/auth/application/private.ts',
  'modules/auth/domain/laundered-consumer.ts crosses into modules/sites/domain/private.ts; cross-module imports must target application/public.ts',
  'modules/auth/domain/laundered-consumer.ts may not depend on modules/auth/application/private.ts',
  'modules/auth/domain/local-barrel.ts crosses into modules/sites/domain/private.ts; cross-module imports must target application/public.ts',
  'modules/auth/domain/nonliteral-imports.ts has a non-literal import() dependency; architecture dependencies must use string literals',
  'modules/auth/domain/nonliteral-imports.ts has a non-literal require() dependency; architecture dependencies must use string literals',
  'modules/auth/infrastructure/wrong-providers.ts may not consume AWS SDK symbol S3Client outside modules/media/infrastructure',
  'modules/auth/infrastructure/wrong-providers.ts may not consume Resend symbol Resend outside modules/notifications/infrastructure',
  'modules/auth/infrastructure/wrong-providers.ts may not import @aws-sdk/client-s3; AWS SDK belongs in modules/media/infrastructure',
  'modules/auth/infrastructure/wrong-providers.ts may not import @resend/node; Resend belongs in modules/notifications/infrastructure',
  'modules/media/infrastructure/resend-denied.ts may not consume Resend symbol Resend outside modules/notifications/infrastructure',
  'modules/media/infrastructure/resend-denied.ts may not import resend; Resend belongs in modules/notifications/infrastructure',
  'modules/notifications/infrastructure/aws-denied.ts may not consume AWS SDK symbol S3Client outside modules/media/infrastructure',
  'modules/notifications/infrastructure/aws-denied.ts may not import @aws-sdk/client-s3; AWS SDK belongs in modules/media/infrastructure',
  'shared/audit/prisma-writer.ts may not consume Prisma-origin symbol PrismaClient outside approved infrastructure adapters',
  'shared/audit/prisma-writer.ts may not import @prisma/client; Prisma access belongs in approved infrastructure adapters',
  'shared/idempotency/prisma-idempotency-writer.ts may not consume Prisma-origin symbol PrismaClient outside approved infrastructure adapters',
  'shared/idempotency/prisma-idempotency-writer.ts may not import @prisma/client; Prisma access belongs in approved infrastructure adapters',
  'shared/provider-derived.ts may not consume AWS SDK symbol S3Client outside modules/media/infrastructure',
  'shared/provider-derived.ts may not consume Prisma-origin symbol PrismaClient outside approved infrastructure adapters',
  'shared/provider-derived.ts may not consume Resend symbol Resend outside modules/notifications/infrastructure',
  'shared/provider-derived.ts may not import @aws-sdk/client-s3; AWS SDK belongs in modules/media/infrastructure',
  'shared/provider-derived.ts may not import @prisma/client; Prisma access belongs in approved infrastructure adapters',
  'shared/provider-derived.ts may not import resend; Resend belongs in modules/notifications/infrastructure',
  'shared/restricted.barrel.ts may not consume AWS SDK symbol ProviderTypes outside modules/media/infrastructure',
  'shared/restricted.barrel.ts may not consume AWS SDK symbol StorageConditional outside modules/media/infrastructure',
  'shared/restricted.barrel.ts may not consume Prisma-origin symbol DataReference outside approved infrastructure adapters',
  'shared/restricted.barrel.ts may not consume Prisma-origin symbol ProviderTypes outside approved infrastructure adapters',
  'shared/restricted.barrel.ts may not consume Resend symbol MailAlias outside modules/notifications/infrastructure',
  'shared/restricted.barrel.ts may not consume Resend symbol ProviderTypes outside modules/notifications/infrastructure',
] as const;
