export const p101RegressionExpectedViolations = [
  'modules/auth/api/bound-controller-entry.ts controller may not consume Resend symbol Resend',
  'modules/auth/api/bound-controller-entry.ts controller may not import provider SDK resend',
  'modules/auth/api/bound-controller-entry.ts may not consume Resend symbol Resend outside modules/notifications/infrastructure',
  'modules/auth/api/bound-controller-entry.ts may not import resend; Resend belongs in modules/notifications/infrastructure',
  'modules/auth/api/composite-controller-entry.ts controller may not consume AWS SDK symbol S3Client',
  'modules/auth/api/composite-controller-entry.ts controller may not import provider SDK @aws-sdk/client-s3',
  'modules/auth/api/composite-controller-entry.ts may not consume AWS SDK symbol S3Client outside modules/media/infrastructure',
  'modules/auth/api/composite-controller-entry.ts may not import @aws-sdk/client-s3; AWS SDK belongs in modules/media/infrastructure',
  'modules/auth/api/handler-entry.ts route handler HandlerEntry.aliasWrong must delegate to exactly one application use case; found 1; non-application dependencies: domain',
  'modules/auth/api/handler-entry.ts route handler HandlerEntry.destructuredWrong must delegate to exactly one application use case; found 1; non-application dependencies: domain',
  'modules/auth/api/handler-entry.ts route handler HandlerEntry.directImportWrong must delegate to exactly one application use case; found 1; non-application dependencies: directRunDomain',
  'modules/auth/api/handler-entry.ts route handler HandlerEntry.propertyAliasWrong must delegate to exactly one application use case; found 1; non-application dependencies: domain',
  'modules/auth/api/handler-entry.ts route handler HandlerEntry.reexportWrong must delegate to exactly one application use case; found 1; non-application dependencies: runDomain',
  'modules/auth/api/handler-entry.ts route handler HandlerEntry.reflectApplyWrong must delegate to exactly one application use case; found 1; non-application dependencies: domain',
  'modules/auth/api/handler-entry.ts route handler HandlerEntry.reflectConstructWrong must delegate to exactly one application use case; found 1; non-application dependencies: DomainService',
  'modules/auth/api/handler-entry.ts route handler HandlerEntry.two must delegate to exactly one application use case; found 2',
  'modules/auth/api/handler-entry.ts route handler HandlerEntry.wrong must delegate to exactly one application use case; found 0; non-application dependencies: domain',
  'modules/auth/api/handler-entry.ts route handler HandlerEntry.zero must delegate to exactly one application use case; found 0',
  'modules/auth/api/handler-shadowed-reflect-entry.ts route handler HandlerShadowedReflectEntry.control must delegate to exactly one application use case; found 1; non-application dependencies: {}',
  'modules/auth/api/nested-controller-entry.ts controller may not consume AWS SDK symbol S3Client',
  'modules/auth/api/nested-controller-entry.ts controller may not import provider SDK @aws-sdk/client-s3',
  'modules/auth/api/nested-controller-entry.ts may not consume AWS SDK symbol S3Client outside modules/media/infrastructure',
  'modules/auth/api/nested-controller-entry.ts may not import @aws-sdk/client-s3; AWS SDK belongs in modules/media/infrastructure',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.alias must delegate to exactly one application use case; found 0',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.arrow must delegate to exactly one application use case; found 0',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.bound must delegate to exactly one application use case; found 0',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.composite must delegate to exactly one application use case; found 0',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.direct must delegate to exactly one application use case; found 0',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.namespace must delegate to exactly one application use case; found 0',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.namespaceAlias must delegate to exactly one application use case; found 0',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.namespaceDestructured must delegate to exactly one application use case; found 0',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.nested must delegate to exactly one application use case; found 0',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.nestedBound must delegate to exactly one application use case; found 0',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.propertyAlias must delegate to exactly one application use case; found 0',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.propertyDestructured must delegate to exactly one application use case; found 0',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.reexport must delegate to exactly one application use case; found 0',
  'modules/auth/api/route-wrapper-entry.ts route handler RouteWrapperEntry.shorthandProperty must delegate to exactly one application use case; found 0',
  'modules/auth/application/adapter-consumer.ts may not consume Prisma-origin symbol AuditGateway outside approved infrastructure adapters',
  'modules/auth/application/adapter-consumer.ts may not consume Prisma-origin symbol expose outside approved infrastructure adapters',
  'modules/auth/application/public.ts application/public.ts may not export HiddenConcrete; only same-module application type/interface contracts and Symbol DI tokens are public',
  'modules/auth/application/public.ts application/public.ts may not export HiddenDomain; only same-module application type/interface contracts and Symbol DI tokens are public',
  'modules/auth/application/public.ts application/public.ts may not export HiddenDomainInterface; only same-module application type/interface contracts and Symbol DI tokens are public',
  'modules/auth/application/public.ts application/public.ts may not export RUNTIME_VALUE; only same-module application type/interface contracts and Symbol DI tokens are public',
  'modules/auth/application/recursive-consumer.ts may not consume Prisma-origin symbol RecursiveA outside approved infrastructure adapters',
  'modules/auth/application/recursive-consumer.ts may not consume Prisma-origin symbol RecursiveB outside approved infrastructure adapters',
  'modules/auth/application/shared-public-consumer.ts crosses into modules/sites/application/public.ts; cross-module imports must target application/public.ts',
  'modules/auth/domain/default-wrapper-consumer.ts crosses into modules/sites/domain/default-private.ts; cross-module imports must target application/public.ts',
  'modules/auth/domain/interface-wrapper-consumer.ts crosses into modules/sites/domain/interface-private.ts; cross-module imports must target application/public.ts',
  'modules/auth/domain/symlink-consumer.ts crosses into modules/sites/domain/symlink-private.ts; cross-module imports must target application/public.ts',
  'modules/auth/domain/type-wrapper-consumer.ts crosses into modules/sites/domain/type-private.ts; cross-module imports must target application/public.ts',
  'modules/auth/domain/value-wrapper-consumer.ts crosses into modules/sites/domain/value-private.ts; cross-module imports must target application/public.ts',
  'shared/audit/infrastructure/r2-recovery-audit-store.ts may not consume AWS SDK symbol S3Client outside modules/media/infrastructure',
  'shared/audit/infrastructure/r2-recovery-audit-store.ts may not import @aws-sdk/client-s3; AWS SDK belongs in modules/media/infrastructure',
  'shared/database.ts may not consume Prisma-origin symbol PrismaClient outside approved infrastructure adapters',
  'shared/database.ts may not import @prisma/client; Prisma access belongs in approved infrastructure adapters',
] as const;
